# Generated by Django 3.1.6 on 2021-02-07 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210207_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 7, 11, 6, 3, 95347)),
        ),
    ]
