# Generated by Django 3.1.6 on 2021-02-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210207_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
