# Generated by Django 3.1.6 on 2021-02-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210207_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='legs',
            field=models.SmallIntegerField(default=4),
        ),
    ]
